title: Hayden Writes
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.437276
  brandStrength: 0.8125
  lightness: 1
  brandColors:
    - '#041d22'
    - '#8f8583'
    - '#b3aeb4'
    - '#006184'
    - '#fff7ec'
  rhythmicContrast: 0
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Hayden Writes
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.9354839
layout_spectrum: 0.74303
