name: Hayden Writes
favicon: null
layout_spectrum: 0.48608
typography_spectrum: 0.5962
title: Hayden Writes
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#041d22'
    - '#8f8583'
    - '#b3aeb4'
    - '#006184'
    - '#fff7ec'
  brandStrength: 0.6526492116972804
  lightness: 0.905380969401449
  saturation: 0.6875
  rhythmicContrast: 0.08246150705963373
purpose: []
