name: Hayden Writes
favicon: null
layout_spectrum: 0.48608
typography_spectrum: 0.5962
title: Hayden Writes
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.6526492116972804
  lightness: 0.905380969401449
  saturation: 0.19525669398717582
  rhythmicContrast: 0.08246150705963373
purpose: []
